# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MaterialCosmicMindStudies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaterialCosmicMindStudies
  pod 'Material', '~> 2.10.0'
  pod 'Graph', '~> 2.1.4'
  pod 'CleanroomLogger', '~> 5.1'  

end
